### PR TITLE
Function 'netServiceDidResolveAddress' is only called once

### PR DESCRIPTION
**Pull request by Sevenstax-bme**
In my project, I got 4 devices in my network and I want to list them with the cordova zeroconf plugin.
All devices are found in the 'betServiceBowser' function:
2015-07-21 11:07:04.127 Application[759:392733] regType: _http._tcp, domain: local.
2015-07-21 11:07:04.129 Application[759:392733] didFindService name Device_1
2015-07-21 11:07:04.132 Application[759:392733] didFindService name Device_2
2015-07-21 11:07:04.134 Application[759:392733] didFindService name Device_3
2015-07-21 11:07:04.137 Application[759:392733] didFindService name Device_4 

But the function 'netServiceDidResolveAddress' is only called once for the last device:
2015-07-21 11:07:04.167 Application[759:392733] netServiceDidResolveAddress: <NSNetService 0x156b7030> local. _http._tcp. Device_4 

I'm using:
iPad 3 -> iOS 8.3
Xcode -> 6.4
Cordova -> 5.1.1

Any idea, would is working wrong?

Thanks for any help

### CODE REVIEW

**Comment by vstirbu** [comment]
I'm a bit confused about this pull request. It contains basically the iOS implementation equivalent to the existing Android. However, the comment looks like a new issue.

**Comment by Sevenstax-bme** [comment]
Maybe I added it wrong, my fault!

Yes it is a new issue for the iOS implementation.
Can I move this to the issue's?

**Comment by vstirbu** [comment]
How on par with the Andorra is the iOS implementation?

**Comment by Sevenstax-bme** [comment]
I figured out a solution for my project by adapting the object-c code for the ios project.
So we can close this "wrong" pull request. I will try to adapt it in the ios fork

**Pull request closed without merging**
